[package]
name = "serial"
version = "0.1.0"
edition = "2021"

[lib]
name = "serial"

[dependencies]
spin = "0.9.8"
uart_16550 = "0.2.19"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
