[package]
name = "serial"
version = "0.1.0"
edition = "2018"


[dependencies]
x86_64 = { workspace = true }
spin = "0.9.8"
uart_16550 = "0.2.0"

[dependencies.lazy_static]
version = "1.0"
features = ["spin_no_std"]
